type ShadowSizes =
  | 'shadow-sm'
  | 'shadow-md'
  | 'shadow-lg'
  | 'shadow-xl'
  | 'shadow-2xl'
  | 'shadow-inner'
  | 'shadow-outline'
  | 'shadow-none'
type DisabledShadowSizes =
  | 'disabled:shadow-sm'
  | 'disabled:shadow-md'
  | 'disabled:shadow-lg'
  | 'disabled:shadow-xl'
  | 'disabled:shadow-2xl'
  | 'disabled:shadow-inner'
  | 'disabled:shadow-outline'
  | 'disabled:shadow-none'
